name: SAST-Semgrep
on: [push, pull_request]

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: semgrep/semgrep-action@v1
        with:
          config: p/owasp-top-ten
          generateSarif: true
          
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif












